StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65DA9B16AA1A0BCA}" {
   Id "SPC-Ammo_9K119_Name"
   Target_en_us "Refleks"
   Modified 1708825768
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65DA9B16A10BF38E}" {
   Id "SPC-Ammo_9K119M1_Name"
   Target_en_us "Invar"
   Modified 1708825780
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65DA9B16AE1BD456}" {
   Id "SPC-Ammo_9K119M_Name"
   Target_en_us "Refleks-M"
   Modified 1708825799
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65DA9B16AD8CF87B}" {
   Id "SPC-Ammo_9M112_Name"
   Target_en_us "Kobra"
   Modified 1708827303
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{655556C1A23B9C53}" {
   Id "SPC-AmmunitionID_105x617mmR"
   Target_en_us "105×617mmR"
   Modified 1700092318
   Author "thoma"
   LastChanged "thoma"
  }
  CustomStringTableItem "{648567337D917CA9}" {
   Id "SPC-AmmunitionID_120x44mm"
   Target_en_us "120×570mm"
   Modified 1700092326
   Author "thoma"
   LastChanged "thoma"
  }
  CustomStringTableItem "{64856733748E32D6}" {
   Id "SPC-AmmunitionID_125x48mm"
   Target_en_us "125×547mm"
   Modified 1700092384
   Author "thoma"
   LastChanged "thoma"
  }
  CustomStringTableItem "{64D4419422AD66E9}" {
   Id "SPC-AmmunitionID_30x165mm"
   Target_en_us "30×165mm"
   Modified 1691634826
   Author "SpaceStrider"
   LastChanged "SpaceStrider"
  }
  CustomStringTableItem "{64F452E83889E3BF}" {
   Id "SPC-AmmunitionID_40x53mm-SR"
   Target_en_us "40x53mm-SR"
   Modified 1693733907
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64EA224F571D3044}" {
   Id "SPC-AmmunitionType_AP-T"
   Target_en_us "AP-T"
   Modified 1693066189
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64856C5ABD039DEB}" {
   Id "SPC-AmmunitionType_APFSDS"
   Target_en_us "APFSDS"
   Modified 1691903674
   Author "thoma"
   LastChanged "SpaceStrider"
  }
  CustomStringTableItem "{64856C5A6A42E53A}" {
   Id "SPC-AmmunitionType_APFSDST"
   Target_en_us "APFSDS-T"
   Modified 1691903685
   Author "thoma"
   LastChanged "SpaceStrider"
  }
  CustomStringTableItem "{64856C5A51D2DA69}" {
   Id "SPC-AmmunitionType_HEATFS"
   Target_en_us "HEAT-FS"
   Modified 1693064262
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64EA224F48F1E711}" {
   Id "SPC-AmmunitionType_HEF-I"
   Target_en_us "HEF-I"
   Modified 1693066194
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64856C5A5CBD03C3}" {
   Id "SPC-AmmunitionType_HEFRAG"
   Target_en_us "HE-FRAG "
   Modified 1693064426
   Author "thoma"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64F443D8A10FF0F1}" {
   Id "SPC-Editor_ContentBrowser_Filter_VEHICLE_BOAT_Name"
   Target_en_us "Boats"
   Modified 1693729857
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64F164017A3E893B}" {
   Id "SPC-Editor_ContentBrowser_Filter_VEHICLE_TANK_Name"
   Target_en_us "Tanks"
   Modified 1693543052
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64D44196EA6ED89F}" {
   Id "SPC-Magazine_2A42_AP_Name"
   Target_en_us "2A42"
   Modified 1691903709
   Author "SpaceStrider"
   LastChanged "SpaceStrider"
  }
  CustomStringTableItem "{64D44196E95D260B}" {
   Id "SPC-Magazine_2A42_HE_Name"
   Target_en_us "2A42"
   Modified 1691903715
   Author "SpaceStrider"
   LastChanged "SpaceStrider"
  }
  CustomStringTableItem "{64D44192C4EDF7E6}" {
   Id "SPC-Weapon_2A42_Description"
   Modified 1691632450
   Author "SpaceStrider"
   LastChanged "SpaceStrider"
  }
  CustomStringTableItem "{64D44192DBB88F47}" {
   Id "SPC-Weapon_2A42_Name"
   Target_en_us "2A42"
   Modified 1691903718
   Author "SpaceStrider"
   LastChanged "SpaceStrider"
  }
  CustomStringTableItem "{65CF5BE10F81626C}" {
   Id "SPC-Weapon_2A46_Name"
   Target_en_us "2A46"
   Modified 1708091577
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64EA224F164912D3}" {
   Id "SPC-Weapon_2A72_Name"
   Target_en_us "2A72"
   Modified 1693066070
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65DA9179475A9732}" {
   Id "SPC-Weapon_9M112_Name"
   Target_en_us "9M112"
   Modified 1708823767
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65D214A6434BD29B}" {
   Id "SPC-Weapon_9M119_Name"
   Target_en_us "9M119"
   Modified 1708267515
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65DA91796F445CBD}" {
   Id "SPC-Weapon_9M119M1_Name"
   Target_en_us "9M119M1"
   Modified 1708823814
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65DA9179736EB95E}" {
   Id "SPC-Weapon_9M119M_Name"
   Target_en_us "9M119M"
   Modified 1708823791
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65D173D305618C10}" {
   Id "SPC-Weapon_KORD_Name"
   Target_en_us "KORD"
   Modified 1708226228
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64F5458CC98F40F9}" {
   Id "SPC-Weapon_M240_Name"
   Modified 1693796326
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64DA118C965261E5}" {
   Id "SPC-Weapon_M256_Name"
   Target_en_us "M256"
   Modified 1692013325
   Author "SpaceStrider"
   LastChanged "SpaceStrider"
  }
  CustomStringTableItem "{64F5458CDB59A274}" {
   Id "SPC-Weapon_M2HB_Name"
   Target_en_us "M2HB"
   Modified 1693796305
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64F452E8F6C3C6B4}" {
   Id "SPC-Weapon_MK19_Name"
   Target_en_us "MK19"
   Modified 1693733811
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64D2276F75982990}" {
   Id "SPC-Weapon_MLRS_Description"
   Modified 1691495291
   Author "SpaceStrider"
   LastChanged "SpaceStrider"
  }
  CustomStringTableItem "{64D2276FA8CF2FC0}" {
   Id "SPC-Weapon_MLRS_M26_Description"
   Modified 1691495452
   Author "SpaceStrider"
   LastChanged "SpaceStrider"
  }
  CustomStringTableItem "{64D2276F4C4FDD92}" {
   Id "SPC-Weapon_MLRS_M26_Name"
   Target_en_us "M26 Cluster MLRS Pod"
   Modified 1691495698
   Author "SpaceStrider"
   LastChanged "SpaceStrider"
  }
  CustomStringTableItem "{64D2276F94B46B9F}" {
   Id "SPC-Weapon_MLRS_M31_Description"
   Modified 1691495458
   Author "SpaceStrider"
   LastChanged "SpaceStrider"
  }
  CustomStringTableItem "{64D2276F5D37F201}" {
   Id "SPC-Weapon_MLRS_M31_Name"
   Target_en_us "M31 HE MLRS Pod"
   Modified 1691495716
   Author "SpaceStrider"
   LastChanged "SpaceStrider"
  }
  CustomStringTableItem "{64D2276F0EEA502E}" {
   Id "SPC-Weapon_MLRS_Name"
   Target_en_us "MLRS Pod"
   Modified 1691495631
   Author "SpaceStrider"
   LastChanged "SpaceStrider"
  }
  CustomStringTableItem "{65A52642B9085135}" {
   Id "VAPE-ActionContextUIInfo_DukeToggleOffAction"
   Target_en_us "AN/VLQ-12 Off"
   Modified 1705322585
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65A5264284954FF2}" {
   Id "VAPE-ActionContextUIInfo_DukeToggleOnAction"
   Target_en_us "AN/VLQ-12 On"
   Modified 1705322581
   Author "mikia"
   LastChanged "mikia"
  }
 }
}